### ISSUE TITLE
"Resource not accessible by integration" when running

### ISSUE THREAD

**Issue by bra1n** [Zomzog/changelog-checker#23]
Hi there,

I tried setting up this action with the following config:
```
name: Enforce Changelog Update
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - main
jobs:
  build:
    name: Check Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Changelog check
        uses: Zomzog/changelog-checker@v1.1.0
        with:
          fileName: CHANGELOG.md
          noChangelogLabel: no changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
Now when there's a PR against main, the action is running but always outputs the following error (and still passes the check even when no changelog change has been made):
```
Run Zomzog/changelog-checker@v1.1.0
(node:1485) UnhandledPromiseRejectionWarning: HttpError: Resource not accessible by integration
    at /home/runner/work/_actions/Zomzog/changelog-checker/v1.1.0/dist/index.js:7752:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1485) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1485) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
The `CHANGELOG.md` file is present in the root of the project, so I'm not sure what else I could do to fix it?

**Comment by Zomzog** [comment]
Hi,
I've reproduced the issue when the PR is from a fork.
I will try to find a solution.

**Comment by bra1n** [comment]
Maybe it tries to get write access when read access would be sufficient?
See: https://github.com/actions/first-interaction/issues/10

**Comment by Zomzog** [comment]
The write access is used for creating a more detailed label.
I've added a new option to disable it.
Please try this configuration : 
```
name: Enforce Changelog Update
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - main
jobs:
  build:
    name: Check Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Changelog check
        uses: Zomzog/changelog-checker@v1.2.0
        with:
          fileName: CHANGELOG.md
          noChangelogLabel: no changelog
          checkNotification: Simple
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
